// Données unifiées des 60 zones MediaHub Campus (réseau Universités + réseau Lycées),
// extraites du classeur Excel "Régie Tarification Finale.xlsx" (feuilles TARIFS_CAMPUS
// et TARIFS_LYCEES, mise à jour du 29/09/2026 12:32). Ne pas éditer à la main :
// régénérer depuis l'Excel si les tarifs ou le réseau changent.

export interface ZoneCampusData {
  /** Audience d'affichage de la zone (fixe, ne dépend pas de la durée) */
  audience: number;
  /** Population étudiante totale de la zone (indicatif, "ND" dans l'Excel pour certaines zones) */
  totalEtudiants: number | null;
  /** Occasions de voir sur 4 semaines */
  odv4sem: number;
  /** Nombre d'affiches A2 posées sur 4 semaines (pack complet) */
  nbAffiches: number;
  /** Budget HT de base pour 4 semaines, pack complet (avant coefficients et dégressif) */
  budgetBase4sem: number;
  /** Nombre réel de lignes (établissements) recensés dans BASE_CAMPUS pour la zone */
  nbLignesReel: number;
  /** Prix unitaire de ciblage : tarif par établissement quand on cible moins que le pack complet */
  prixUnitaireCiblage: number;
  /** Nombre de villes distinctes que compte la zone (attribut fixe) */
  nbVillesDistinctes: number;
  /** Coefficient de dispersion géographique, fixe par zone (barème PARAMETRES du 29/09/2026) */
  coefDispersion: number;
}

export interface ZoneLyceeData {
  /** Nombre de lycées du réseau sur la zone */
  nbLycees: number;
  /** Effectifs lycéens couverts par le réseau sur la zone */
  effectifs: number;
  /** Nombre d'affiches A2 posées sur 4 semaines (pack complet) */
  nbAffiches: number;
  /** Budget HT de base pour 4 semaines, pack complet (avant coefficients et dégressif) */
  budgetBase4sem: number;
  /** Prix unitaire de ciblage : tarif par lycée quand on cible moins que le pack complet */
  prixUnitaireCiblage: number;
  /** Nombre de villes distinctes que compte la zone (attribut fixe) */
  nbVillesDistinctes: number;
  /** Coefficient de dispersion géographique, fixe par zone (barème PARAMETRES du 29/09/2026) */
  coefDispersion: number;
}

export interface MhcZone {
  zone: string;
  region: string;
  departement: string;
  /** Absent si la zone n'a aucun établissement du réseau Universités (ex. Béziers) */
  campus: ZoneCampusData | null;
  lycee: ZoneLyceeData;
}

export const MHC_ZONES: MhcZone[] = [
  {
    zone: "AGEN",
    region: "Nouvelle-Aquitaine",
    departement: "Lot-et-Garonne",
    campus: {
      audience: 2000,
      totalEtudiants: 3000,
      odv4sem: 160000,
      nbAffiches: 100,
      budgetBase4sem: 750,
      nbLignesReel: 14,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 3,
      coefDispersion: 1.15,
    },
    lycee: {
      nbLycees: 11,
      effectifs: 7080,
      nbAffiches: 33,
      budgetBase4sem: 495,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 6,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "AIX-EN-PROVENCE",
    region: "Provence-Alpes-Côte d’Azur",
    departement: "Bouches-du-Rhône",
    campus: {
      audience: 30000,
      totalEtudiants: 40000,
      odv4sem: 2400000,
      nbAffiches: 150,
      budgetBase4sem: 1250,
      nbLignesReel: 33,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 29,
      effectifs: 10998,
      nbAffiches: 87,
      budgetBase4sem: 1305,
      prixUnitaireCiblage: 136.4318182,
      nbVillesDistinctes: 4,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "AMIENS",
    region: "Hauts-de-France",
    departement: "Somme",
    campus: {
      audience: 30000,
      totalEtudiants: 38000,
      odv4sem: 2400000,
      nbAffiches: 150,
      budgetBase4sem: 1250,
      nbLignesReel: 35,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 21,
      effectifs: 8500,
      nbAffiches: 63,
      budgetBase4sem: 945,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 6,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "ANGERS",
    region: "Pays de la Loire",
    departement: "Maine-et-Loire",
    campus: {
      audience: 40000,
      totalEtudiants: 50000,
      odv4sem: 3200000,
      nbAffiches: 200,
      budgetBase4sem: 1350,
      nbLignesReel: 34,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 17,
      effectifs: 13780,
      nbAffiches: 51,
      budgetBase4sem: 765,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 7,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "ANNEÇY",
    region: "Auvergne-Rhône-Alpes",
    departement: "Haute-Savoie",
    campus: {
      audience: 8000,
      totalEtudiants: 10000,
      odv4sem: 640000,
      nbAffiches: 100,
      budgetBase4sem: 800,
      nbLignesReel: 9,
      prixUnitaireCiblage: 102.2222222,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 9,
      effectifs: 8280,
      nbAffiches: 27,
      budgetBase4sem: 405,
      prixUnitaireCiblage: 90,
      nbVillesDistinctes: 5,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "AUXERRE",
    region: "Bourgogne-Franche-Comté",
    departement: "Yonne",
    campus: {
      audience: 1100,
      totalEtudiants: 2000,
      odv4sem: 88000,
      nbAffiches: 80,
      budgetBase4sem: 700,
      nbLignesReel: 10,
      prixUnitaireCiblage: 80.5,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 7,
      effectifs: 5750,
      nbAffiches: 21,
      budgetBase4sem: 315,
      prixUnitaireCiblage: 90,
      nbVillesDistinctes: 4,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "AVIGNON",
    region: "Provence-Alpes-Côte d’Azur",
    departement: "Vaucluse",
    campus: {
      audience: 6500,
      totalEtudiants: 10000,
      odv4sem: 520000,
      nbAffiches: 120,
      budgetBase4sem: 950,
      nbLignesReel: 13,
      prixUnitaireCiblage: 84.03846154,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 11,
      effectifs: 10000,
      nbAffiches: 33,
      budgetBase4sem: 495,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 6,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "BAYONNE",
    region: "Nouvelle-Aquitaine",
    departement: "Pyrénées-Atlantiques",
    campus: {
      audience: 2200,
      totalEtudiants: 4000,
      odv4sem: 176000,
      nbAffiches: 120,
      budgetBase4sem: 950,
      nbLignesReel: 18,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 2,
      coefDispersion: 1.15,
    },
    lycee: {
      nbLycees: 33,
      effectifs: 8550,
      nbAffiches: 99,
      budgetBase4sem: 1485,
      prixUnitaireCiblage: 189.75,
      nbVillesDistinctes: 5,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "BEAUVAIS",
    region: "Hauts-de-France",
    departement: "Oise",
    campus: {
      audience: 4500,
      totalEtudiants: 6000,
      odv4sem: 360000,
      nbAffiches: 120,
      budgetBase4sem: 950,
      nbLignesReel: 8,
      prixUnitaireCiblage: 136.5625,
      nbVillesDistinctes: 2,
      coefDispersion: 1.15,
    },
    lycee: {
      nbLycees: 19,
      effectifs: 5700,
      nbAffiches: 57,
      budgetBase4sem: 855,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 6,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "BESANCON",
    region: "Bourgogne-Franche-Comté",
    departement: "Doubs",
    campus: {
      audience: 15000,
      totalEtudiants: 25000,
      odv4sem: 1200000,
      nbAffiches: 120,
      budgetBase4sem: 950,
      nbLignesReel: 23,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 2,
      coefDispersion: 1.15,
    },
    lycee: {
      nbLycees: 17,
      effectifs: 12030,
      nbAffiches: 51,
      budgetBase4sem: 765,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 8,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "BEZIER",
    region: "Occitanie",
    departement: "Hérault",
    campus: null,
    lycee: {
      nbLycees: 31,
      effectifs: 7570,
      nbAffiches: 93,
      budgetBase4sem: 1395,
      prixUnitaireCiblage: 145.8409091,
      nbVillesDistinctes: 6,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "BLOIS",
    region: "Centre-Val de Loire",
    departement: "Loir-et-Cher",
    campus: {
      audience: 2000,
      totalEtudiants: 4000,
      odv4sem: 160000,
      nbAffiches: 100,
      budgetBase4sem: 750,
      nbLignesReel: 8,
      prixUnitaireCiblage: 107.8125,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 15,
      effectifs: 8920,
      nbAffiches: 45,
      budgetBase4sem: 675,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 6,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "BORDEAUX",
    region: "Nouvelle-Aquitaine",
    departement: "Gironde",
    campus: {
      audience: 150000,
      totalEtudiants: 220000,
      odv4sem: 12000000,
      nbAffiches: 400,
      budgetBase4sem: 2100,
      nbLignesReel: 63,
      prixUnitaireCiblage: 51.75,
      nbVillesDistinctes: 2,
      coefDispersion: 1.15,
    },
    lycee: {
      nbLycees: 40,
      effectifs: 36360,
      nbAffiches: 120,
      budgetBase4sem: 1800,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 15,
      coefDispersion: 1.7,
    },
  },
  {
    zone: "BOURGES",
    region: "Centre-Val de Loire",
    departement: "Cher",
    campus: {
      audience: 2000,
      totalEtudiants: 5000,
      odv4sem: 160000,
      nbAffiches: 100,
      budgetBase4sem: 750,
      nbLignesReel: 7,
      prixUnitaireCiblage: 123.2142857,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 16,
      effectifs: 10180,
      nbAffiches: 48,
      budgetBase4sem: 720,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 7,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "BREST",
    region: "Bretagne",
    departement: "Finistère",
    campus: {
      audience: 20000,
      totalEtudiants: 25000,
      odv4sem: 1600000,
      nbAffiches: 150,
      budgetBase4sem: 1150,
      nbLignesReel: 18,
      prixUnitaireCiblage: 73.47222222,
      nbVillesDistinctes: 2,
      coefDispersion: 1.15,
    },
    lycee: {
      nbLycees: 33,
      effectifs: 11350,
      nbAffiches: 99,
      budgetBase4sem: 1485,
      prixUnitaireCiblage: 113.85,
      nbVillesDistinctes: 6,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "CAEN",
    region: "Normandie",
    departement: "Calvados",
    campus: {
      audience: 25000,
      totalEtudiants: 35000,
      odv4sem: 2000000,
      nbAffiches: 150,
      budgetBase4sem: 1250,
      nbLignesReel: 25,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 4,
      coefDispersion: 1.3,
    },
    lycee: {
      nbLycees: 30,
      effectifs: 20880,
      nbAffiches: 90,
      budgetBase4sem: 1350,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 11,
      coefDispersion: 1.7,
    },
  },
  {
    zone: "CANNES - VALBONNE",
    region: "Provence-Alpes-Côte d’Azur",
    departement: "Alpes-Maritimes",
    campus: {
      audience: 5500,
      totalEtudiants: 7000,
      odv4sem: 440000,
      nbAffiches: 100,
      budgetBase4sem: 1300,
      nbLignesReel: 21,
      prixUnitaireCiblage: 71.19047619,
      nbVillesDistinctes: 7,
      coefDispersion: 1.5,
    },
    lycee: {
      nbLycees: 39,
      effectifs: 13730,
      nbAffiches: 117,
      budgetBase4sem: 1755,
      prixUnitaireCiblage: 112.125,
      nbVillesDistinctes: 7,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "CHAMBERY",
    region: "Auvergne-Rhône-Alpes",
    departement: "Savoie",
    campus: {
      audience: 13000,
      totalEtudiants: 27000,
      odv4sem: 1040000,
      nbAffiches: 150,
      budgetBase4sem: 1150,
      nbLignesReel: 15,
      prixUnitaireCiblage: 88.16666667,
      nbVillesDistinctes: 3,
      coefDispersion: 1.15,
    },
    lycee: {
      nbLycees: 8,
      effectifs: 7300,
      nbAffiches: 24,
      budgetBase4sem: 360,
      prixUnitaireCiblage: 90,
      nbVillesDistinctes: 5,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "CHARTRES",
    region: "Centre-Val de Loire",
    departement: "Eure-et-Loir",
    campus: {
      audience: 1500,
      totalEtudiants: 2000,
      odv4sem: 120000,
      nbAffiches: 80,
      budgetBase4sem: 700,
      nbLignesReel: 10,
      prixUnitaireCiblage: 80.5,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 17,
      effectifs: 11820,
      nbAffiches: 51,
      budgetBase4sem: 765,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 9,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "CHATEAUROUX",
    region: "Centre-Val de Loire",
    departement: "Indre",
    campus: {
      audience: 2000,
      totalEtudiants: null,
      odv4sem: 160000,
      nbAffiches: 80,
      budgetBase4sem: 700,
      nbLignesReel: 7,
      prixUnitaireCiblage: 115,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 13,
      effectifs: 7700,
      nbAffiches: 39,
      budgetBase4sem: 585,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 7,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "CLERMONT-FERRAND",
    region: "Auvergne-Rhône-Alpes",
    departement: "Puy-de-Dôme",
    campus: {
      audience: 75000,
      totalEtudiants: 95000,
      odv4sem: 6000000,
      nbAffiches: 200,
      budgetBase4sem: 1350,
      nbLignesReel: 53,
      prixUnitaireCiblage: 51.75,
      nbVillesDistinctes: 4,
      coefDispersion: 1.3,
    },
    lycee: {
      nbLycees: 12,
      effectifs: 9950,
      nbAffiches: 36,
      budgetBase4sem: 540,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 5,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "COLMAR",
    region: "Grand Est",
    departement: "Haut-Rhin",
    campus: {
      audience: 1500,
      totalEtudiants: 2000,
      odv4sem: 120000,
      nbAffiches: 80,
      budgetBase4sem: 700,
      nbLignesReel: 7,
      prixUnitaireCiblage: 115,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 18,
      effectifs: 4210,
      nbAffiches: 54,
      budgetBase4sem: 810,
      prixUnitaireCiblage: 116.4375,
      nbVillesDistinctes: 4,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "DIJON",
    region: "Bourgogne-Franche-Comté",
    departement: "Côte-d’Or",
    campus: {
      audience: 25000,
      totalEtudiants: 40000,
      odv4sem: 2000000,
      nbAffiches: 150,
      budgetBase4sem: 1250,
      nbLignesReel: 29,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 2,
      coefDispersion: 1.15,
    },
    lycee: {
      nbLycees: 18,
      effectifs: 13000,
      nbAffiches: 54,
      budgetBase4sem: 810,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 7,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "EVREUX",
    region: "Normandie",
    departement: "Eure",
    campus: {
      audience: 3000,
      totalEtudiants: null,
      odv4sem: 240000,
      nbAffiches: 100,
      budgetBase4sem: 750,
      nbLignesReel: 13,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 17,
      effectifs: 11010,
      nbAffiches: 51,
      budgetBase4sem: 765,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 8,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "GRENOBLE",
    region: "Auvergne-Rhône-Alpes",
    departement: "Isère",
    campus: {
      audience: 45000,
      totalEtudiants: 55000,
      odv4sem: 3600000,
      nbAffiches: 200,
      budgetBase4sem: 1350,
      nbLignesReel: 57,
      prixUnitaireCiblage: 51.75,
      nbVillesDistinctes: 5,
      coefDispersion: 1.3,
    },
    lycee: {
      nbLycees: 19,
      effectifs: 15729,
      nbAffiches: 57,
      budgetBase4sem: 855,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 9,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "LA ROCHE-SUR-YON",
    region: "Pays de la Loire",
    departement: "Vendée",
    campus: {
      audience: 7000,
      totalEtudiants: 10000,
      odv4sem: 560000,
      nbAffiches: 100,
      budgetBase4sem: 800,
      nbLignesReel: 11,
      prixUnitaireCiblage: 83.63636364,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 11,
      effectifs: 8350,
      nbAffiches: 33,
      budgetBase4sem: 495,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 7,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "LA ROCHELLE",
    region: "Nouvelle-Aquitaine",
    departement: "Charente-Maritime",
    campus: {
      audience: 12000,
      totalEtudiants: 15000,
      odv4sem: 960000,
      nbAffiches: 150,
      budgetBase4sem: 1150,
      nbLignesReel: 13,
      prixUnitaireCiblage: 101.7307692,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 28,
      effectifs: 10300,
      nbAffiches: 84,
      budgetBase4sem: 1260,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 7,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "LAVAL",
    region: "Pays de la Loire",
    departement: "Mayenne",
    campus: {
      audience: 5000,
      totalEtudiants: 8000,
      odv4sem: 400000,
      nbAffiches: 150,
      budgetBase4sem: 1150,
      nbLignesReel: 13,
      prixUnitaireCiblage: 101.7307692,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 19,
      effectifs: 8300,
      nbAffiches: 57,
      budgetBase4sem: 855,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 5,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "LE HAVRE",
    region: "Normandie",
    departement: "Seine-Maritime",
    campus: {
      audience: 9000,
      totalEtudiants: 12000,
      odv4sem: 720000,
      nbAffiches: 150,
      budgetBase4sem: 1150,
      nbLignesReel: 21,
      prixUnitaireCiblage: 62.97619048,
      nbVillesDistinctes: 2,
      coefDispersion: 1.15,
    },
    lycee: {
      nbLycees: 32,
      effectifs: 5250,
      nbAffiches: 96,
      budgetBase4sem: 1440,
      prixUnitaireCiblage: 276,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
  },
  {
    zone: "LE MANS",
    region: "Pays de la Loire",
    departement: "Sarthe",
    campus: {
      audience: 9000,
      totalEtudiants: 13000,
      odv4sem: 720000,
      nbAffiches: 150,
      budgetBase4sem: 1150,
      nbLignesReel: 24,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 21,
      effectifs: 9450,
      nbAffiches: 63,
      budgetBase4sem: 945,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 6,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "LILLE",
    region: "Hauts-de-France",
    departement: "Nord",
    campus: {
      audience: 90000,
      totalEtudiants: 110000,
      odv4sem: 7200000,
      nbAffiches: 400,
      budgetBase4sem: 1800,
      nbLignesReel: 52,
      prixUnitaireCiblage: 51.75,
      nbVillesDistinctes: 4,
      coefDispersion: 1.3,
    },
    lycee: {
      nbLycees: 106,
      effectifs: 15470,
      nbAffiches: 318,
      budgetBase4sem: 4770,
      prixUnitaireCiblage: 76.1875,
      nbVillesDistinctes: 22,
      coefDispersion: 2,
    },
  },
  {
    zone: "LIMOGES",
    region: "Nouvelle-Aquitaine",
    departement: "Haute-Vienne",
    campus: {
      audience: 10000,
      totalEtudiants: 18000,
      odv4sem: 800000,
      nbAffiches: 120,
      budgetBase4sem: 950,
      nbLignesReel: 31,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 11,
      effectifs: 9250,
      nbAffiches: 33,
      budgetBase4sem: 495,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 7,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "LORIENT",
    region: "Bretagne",
    departement: "Morbihan",
    campus: {
      audience: 4000,
      totalEtudiants: 6000,
      odv4sem: 320000,
      nbAffiches: 100,
      budgetBase4sem: 800,
      nbLignesReel: 5,
      prixUnitaireCiblage: 184,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 10,
      effectifs: 7070,
      nbAffiches: 30,
      budgetBase4sem: 450,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 6,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "LYON",
    region: "Auvergne-Rhône-Alpes",
    departement: "Rhône",
    campus: {
      audience: 110000,
      totalEtudiants: 150000,
      odv4sem: 8800000,
      nbAffiches: 400,
      budgetBase4sem: 1800,
      nbLignesReel: 137,
      prixUnitaireCiblage: 51.75,
      nbVillesDistinctes: 17,
      coefDispersion: 2,
    },
    lycee: {
      nbLycees: 16,
      effectifs: 16750,
      nbAffiches: 48,
      budgetBase4sem: 720,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 13,
      coefDispersion: 1.7,
    },
  },
  {
    zone: "MARSEILLE",
    region: "Provence-Alpes-Côte d’Azur",
    departement: "Bouches-du-Rhône",
    campus: {
      audience: 45000,
      totalEtudiants: 65000,
      odv4sem: 3600000,
      nbAffiches: 200,
      budgetBase4sem: 1350,
      nbLignesReel: 50,
      prixUnitaireCiblage: 51.75,
      nbVillesDistinctes: 8,
      coefDispersion: 1.5,
    },
    lycee: {
      nbLycees: 29,
      effectifs: 17350,
      nbAffiches: 87,
      budgetBase4sem: 1305,
      prixUnitaireCiblage: 83.375,
      nbVillesDistinctes: 11,
      coefDispersion: 1.7,
    },
  },
  {
    zone: "METZ",
    region: "Grand Est",
    departement: "Moselle",
    campus: {
      audience: 20000,
      totalEtudiants: 25000,
      odv4sem: 1600000,
      nbAffiches: 150,
      budgetBase4sem: 1150,
      nbLignesReel: 23,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 2,
      coefDispersion: 1.15,
    },
    lycee: {
      nbLycees: 13,
      effectifs: 10170,
      nbAffiches: 39,
      budgetBase4sem: 585,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 6,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "MONTPELLIER",
    region: "Occitanie",
    departement: "Hérault",
    campus: {
      audience: 60000,
      totalEtudiants: 75000,
      odv4sem: 4800000,
      nbAffiches: 200,
      budgetBase4sem: 1350,
      nbLignesReel: 67,
      prixUnitaireCiblage: 51.75,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 31,
      effectifs: 21009,
      nbAffiches: 93,
      budgetBase4sem: 1395,
      prixUnitaireCiblage: 80.2125,
      nbVillesDistinctes: 6,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "MULHOUSE",
    region: "Grand Est",
    departement: "Haut-Rhin",
    campus: {
      audience: 5000,
      totalEtudiants: 7000,
      odv4sem: 400000,
      nbAffiches: 100,
      budgetBase4sem: 800,
      nbLignesReel: 18,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 18,
      effectifs: 9350,
      nbAffiches: 54,
      budgetBase4sem: 810,
      prixUnitaireCiblage: 93.15,
      nbVillesDistinctes: 4,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "NANCY",
    region: "Grand Est",
    departement: "Meurthe-et-Moselle",
    campus: {
      audience: 45000,
      totalEtudiants: 55000,
      odv4sem: 3600000,
      nbAffiches: 200,
      budgetBase4sem: 1350,
      nbLignesReel: 47,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 7,
      coefDispersion: 1.5,
    },
    lycee: {
      nbLycees: 18,
      effectifs: 16401,
      nbAffiches: 54,
      budgetBase4sem: 810,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 10,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "NANTES",
    region: "Pays de la Loire",
    departement: "Loire-Atlantique",
    campus: {
      audience: 60000,
      totalEtudiants: 74000,
      odv4sem: 4800000,
      nbAffiches: 200,
      budgetBase4sem: 1350,
      nbLignesReel: 45,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 25,
      effectifs: 16170,
      nbAffiches: 75,
      budgetBase4sem: 1125,
      prixUnitaireCiblage: 80.859375,
      nbVillesDistinctes: 7,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "NICE",
    region: "Provence-Alpes-Côte d’Azur",
    departement: "Alpes-Maritimes",
    campus: {
      audience: 30000,
      totalEtudiants: 40000,
      odv4sem: 2400000,
      nbAffiches: 200,
      budgetBase4sem: 1350,
      nbLignesReel: 46,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 4,
      coefDispersion: 1.3,
    },
    lycee: {
      nbLycees: 39,
      effectifs: 18417,
      nbAffiches: 117,
      budgetBase4sem: 1755,
      prixUnitaireCiblage: 96.10714286,
      nbVillesDistinctes: 7,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "NIMES",
    region: "Occitanie",
    departement: "Gard",
    campus: {
      audience: 15000,
      totalEtudiants: 20000,
      odv4sem: 1200000,
      nbAffiches: 200,
      budgetBase4sem: 1350,
      nbLignesReel: 22,
      prixUnitaireCiblage: 70.56818182,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 19,
      effectifs: 15950,
      nbAffiches: 57,
      budgetBase4sem: 855,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 8,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "ORLEANS",
    region: "Centre-Val de Loire",
    departement: "Loiret",
    campus: {
      audience: 20000,
      totalEtudiants: 25000,
      odv4sem: 1600000,
      nbAffiches: 150,
      budgetBase4sem: 1150,
      nbLignesReel: 27,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 28,
      effectifs: 13210,
      nbAffiches: 84,
      budgetBase4sem: 1260,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 9,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "PAU",
    region: "Nouvelle-Aquitaine",
    departement: "Pyrénées-Atlantiques",
    campus: {
      audience: 10000,
      totalEtudiants: 15000,
      odv4sem: 800000,
      nbAffiches: 120,
      budgetBase4sem: 950,
      nbLignesReel: 12,
      prixUnitaireCiblage: 91.04166667,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 33,
      effectifs: 7580,
      nbAffiches: 99,
      budgetBase4sem: 1485,
      prixUnitaireCiblage: 71.15625,
      nbVillesDistinctes: 8,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "PERPIGNAN",
    region: "Occitanie",
    departement: "Pyrénées-Orientales",
    campus: {
      audience: 7000,
      totalEtudiants: 10000,
      odv4sem: 560000,
      nbAffiches: 150,
      budgetBase4sem: 1150,
      nbLignesReel: 16,
      prixUnitaireCiblage: 82.65625,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 11,
      effectifs: 8450,
      nbAffiches: 33,
      budgetBase4sem: 495,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 6,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "POITIERS",
    region: "Nouvelle-Aquitaine",
    departement: "Vienne",
    campus: {
      audience: 15000,
      totalEtudiants: 25000,
      odv4sem: 1200000,
      nbAffiches: 150,
      budgetBase4sem: 1150,
      nbLignesReel: 34,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 9,
      effectifs: 8400,
      nbAffiches: 27,
      budgetBase4sem: 405,
      prixUnitaireCiblage: 90,
      nbVillesDistinctes: 5,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "QUIMPER",
    region: "Bretagne",
    departement: "Finistère",
    campus: {
      audience: 4000,
      totalEtudiants: 7000,
      odv4sem: 320000,
      nbAffiches: 100,
      budgetBase4sem: 800,
      nbLignesReel: 8,
      prixUnitaireCiblage: 115,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 33,
      effectifs: 11850,
      nbAffiches: 99,
      budgetBase4sem: 1485,
      prixUnitaireCiblage: 94.875,
      nbVillesDistinctes: 8,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "REIMS",
    region: "Grand Est",
    departement: "Marne",
    campus: {
      audience: 25000,
      totalEtudiants: 36000,
      odv4sem: 2000000,
      nbAffiches: 150,
      budgetBase4sem: 1250,
      nbLignesReel: 26,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 30,
      effectifs: 15980,
      nbAffiches: 90,
      budgetBase4sem: 1350,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 6,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "RENNES",
    region: "Bretagne",
    departement: "Ille-et-Vilaine",
    campus: {
      audience: 55000,
      totalEtudiants: 65000,
      odv4sem: 4400000,
      nbAffiches: 200,
      budgetBase4sem: 1350,
      nbLignesReel: 40,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 2,
      coefDispersion: 1.15,
    },
    lycee: {
      nbLycees: 24,
      effectifs: 22412,
      nbAffiches: 72,
      budgetBase4sem: 1080,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 8,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "ROUEN",
    region: "Normandie",
    departement: "Seine-Maritime",
    campus: {
      audience: 35000,
      totalEtudiants: 50000,
      odv4sem: 2800000,
      nbAffiches: 200,
      budgetBase4sem: 1350,
      nbLignesReel: 28,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 4,
      coefDispersion: 1.3,
    },
    lycee: {
      nbLycees: 32,
      effectifs: 10670,
      nbAffiches: 96,
      budgetBase4sem: 1440,
      prixUnitaireCiblage: 63.69230769,
      nbVillesDistinctes: 7,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "SAINT-ETIENNE",
    region: "Auvergne-Rhône-Alpes",
    departement: "Loire",
    campus: {
      audience: 25000,
      totalEtudiants: 35000,
      odv4sem: 2000000,
      nbAffiches: 150,
      budgetBase4sem: 1250,
      nbLignesReel: 45,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 2,
      coefDispersion: 1.15,
    },
    lycee: {
      nbLycees: 17,
      effectifs: 11480,
      nbAffiches: 51,
      budgetBase4sem: 765,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 6,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "SAINT-NAZAIRE",
    region: "Pays de la Loire",
    departement: "Loire-Atlantique",
    campus: {
      audience: 3000,
      totalEtudiants: 5000,
      odv4sem: 240000,
      nbAffiches: 100,
      budgetBase4sem: 750,
      nbLignesReel: 8,
      prixUnitaireCiblage: 107.8125,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 25,
      effectifs: 4550,
      nbAffiches: 75,
      budgetBase4sem: 1125,
      prixUnitaireCiblage: 143.75,
      nbVillesDistinctes: 5,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "STRASBOURG",
    region: "Grand Est",
    departement: "Bas-Rhin",
    campus: {
      audience: 50000,
      totalEtudiants: 60000,
      odv4sem: 4000000,
      nbAffiches: 200,
      budgetBase4sem: 1350,
      nbLignesReel: 55,
      prixUnitaireCiblage: 51.75,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 10,
      effectifs: 10280,
      nbAffiches: 30,
      budgetBase4sem: 450,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 4,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "TOULON - LA GARDE",
    region: "Provence-Alpes-Côte d’Azur",
    departement: "Var",
    campus: {
      audience: 12000,
      totalEtudiants: 15000,
      odv4sem: 960000,
      nbAffiches: 200,
      budgetBase4sem: 1300,
      nbLignesReel: 20,
      prixUnitaireCiblage: 74.75,
      nbVillesDistinctes: 2,
      coefDispersion: 1.15,
    },
    lycee: {
      nbLycees: 10,
      effectifs: 9000,
      nbAffiches: 30,
      budgetBase4sem: 450,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 5,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "TOULOUSE",
    region: "Occitanie",
    departement: "Haute-Garonne",
    campus: {
      audience: 85000,
      totalEtudiants: 110000,
      odv4sem: 6800000,
      nbAffiches: 400,
      budgetBase4sem: 1800,
      nbLignesReel: 27,
      prixUnitaireCiblage: 76.66666667,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 31,
      effectifs: 28610,
      nbAffiches: 93,
      budgetBase4sem: 1395,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 9,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "TOURS",
    region: "Centre-Val de Loire",
    departement: "Indre-et-Loire",
    campus: {
      audience: 25000,
      totalEtudiants: 35000,
      odv4sem: 2000000,
      nbAffiches: 150,
      budgetBase4sem: 1250,
      nbLignesReel: 32,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 1,
      coefDispersion: 1,
    },
    lycee: {
      nbLycees: 36,
      effectifs: 14860,
      nbAffiches: 108,
      budgetBase4sem: 1620,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 9,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "TROYES",
    region: "Grand Est",
    departement: "Aube",
    campus: {
      audience: 7000,
      totalEtudiants: 13000,
      odv4sem: 560000,
      nbAffiches: 200,
      budgetBase4sem: 1350,
      nbLignesReel: 15,
      prixUnitaireCiblage: 103.5,
      nbVillesDistinctes: 2,
      coefDispersion: 1.15,
    },
    lycee: {
      nbLycees: 29,
      effectifs: 8950,
      nbAffiches: 87,
      budgetBase4sem: 1305,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 8,
      coefDispersion: 1.5,
    },
  },
  {
    zone: "VALENCE",
    region: "Auvergne-Rhône-Alpes",
    departement: "Drôme",
    campus: {
      audience: 7000,
      totalEtudiants: 10000,
      odv4sem: 560000,
      nbAffiches: 120,
      budgetBase4sem: 950,
      nbLignesReel: 23,
      prixUnitaireCiblage: 60.75,
      nbVillesDistinctes: 2,
      coefDispersion: 1.15,
    },
    lycee: {
      nbLycees: 12,
      effectifs: 10250,
      nbAffiches: 36,
      budgetBase4sem: 540,
      prixUnitaireCiblage: 72,
      nbVillesDistinctes: 5,
      coefDispersion: 1.3,
    },
  },
  {
    zone: "VALENCIENNES",
    region: "Hauts-de-France",
    departement: "Nord",
    campus: {
      audience: 7000,
      totalEtudiants: 15000,
      odv4sem: 560000,
      nbAffiches: 100,
      budgetBase4sem: 800,
      nbLignesReel: 11,
      prixUnitaireCiblage: 83.63636364,
      nbVillesDistinctes: 2,
      coefDispersion: 1.15,
    },
    lycee: {
      nbLycees: 106,
      effectifs: 7090,
      nbAffiches: 318,
      budgetBase4sem: 4770,
      prixUnitaireCiblage: 161.3382353,
      nbVillesDistinctes: 14,
      coefDispersion: 1.7,
    },
  },
  {
    zone: "ÎLE-DE-FRANCE",
    region: "Île-de-France",
    departement: "Île-de-France",
    campus: {
      audience: 750000,
      totalEtudiants: 950000,
      odv4sem: 60000000,
      nbAffiches: 1000,
      budgetBase4sem: 5500,
      nbLignesReel: 436,
      prixUnitaireCiblage: 45,
      nbVillesDistinctes: 67,
      coefDispersion: 2,
    },
    lycee: {
      nbLycees: 365,
      effectifs: 203582,
      nbAffiches: 1095,
      budgetBase4sem: 16425,
      prixUnitaireCiblage: 51.75,
      nbVillesDistinctes: 126,
      coefDispersion: 2,
    },
  },
];

